name: caching the artifact
on: 
  workflow_dispatch:
    inputs:
      clear_cache:
        description: 'Clear cache before running'
        required: true
        type: boolean
        default: 'false'
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clear cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: |
          echo "Clearing cache..."
          rm -rf $HOME/.npm
      - name: cache node modules
        if: ${{ github.event.inputs.clear_cache == 'false' }}
        id: cache-hit-id
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
      - run: |
          echo "${{toJson(steps.cache-hit-id.outputs)}}"
          cd ~/.npm
          ls -a ~/.npm/_logs
      - run: npm install
      - name: run tests
        run: npm test
      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: coverage
          retention-days: 10
      - name: fetch a random joke
        uses: actions/github-script@v7
        with:
          script: |
            const randomJokeAPI = 'https://official-joke-api.appspot.com/random_joke';
            const axios = require('axios');
            await axios.get(randomJokeAPI)
              .then(response => {
                console.log(response.data);
              })
              .catch(error => {
                console.error('Error fetching joke:', error);
              });
